### ISSUE TITLE
Por que utilizar NPM?

### ISSUE THREAD

**Issue by woliveiras** [gustavoquinalha/jekyll-help-center-theme#1]
@gustavoquinalha, percebi que seu `package.json` só tem a referência ao comando `bundle exec jekyll serve --livereload --watch` no **scripts**, por que usar npm e não utilizar diretamente o bundle no terminal?

Outro ponto: você utiliza o NPM, mas não está instalando nenhum pacote.

```
  "dependencies": {
  },
```

A licença usada no package.json (**ISC**) também não é a licença do projeto (**MIT**). :scream:

Não seria o caso de nem usar o NPM?

**Comment by gustavoquinalha** [comment]
@woliveiras eu tinha algumas dependências, mas troquei pelo CDN. Irei corrigir, obrigado!
